#!/bin/bash

# SSH to the remote server and execute commands
ssh -o StrictHostKeyChecking=no -tt devops@98.70.91.102 <<"EOF"
  cd /home/devops/Fortesting

  # Optional: Stash local changes if needed
  git stash

  # Pull latest changes from the 'dev' branch
  git pull origin dev

  # Checkout 'dev' branch
  git checkout dev

  # Reset to the latest commit on 'dev' branch
 # git reset --hard

  # Pull latest changes again to ensure the latest code
  git pull origin dev

  # Install Python dependencies (assuming you're using pip)
  pip install -r requirements.txt

  # Create a config file
  echo "ENV = 'dev'" > src/config.py

  # Run any migrations or database updates (if needed)
  # python manage.py migrate

  # Restart services or run any other necessary commands

  exit
EOF
